---
name: flutter_chat
description: Chat Flutter app.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.1.1
  firebase_core: ^1.0.3
  firebase_auth: ^1.0.3
  cloud_firestore: ^1.0.4
  modal_progress_hud: ^0.1.3
flutter_icons:
  android: launcher_icon
  ios: true
  image_path: images/launcher_icon/chat_icon.png
dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - images/
